### ISSUE TITLE
response.json() should be called only after checking response.status = OK

### ISSUE THREAD

**Issue by anthonywu** [ambitioninc/newrelic-api#17]
First of all, thank you for this excellent API client. I appreciate you guys sharing your good work.

# Issue #

Sometimes, NewRelic's API responds with Internal Server Error 500, which breaks the assumption that the response object's `json()` method will successfully return.

This is what happens now when the server errors:
```
client.update(6741145, name='blah')
*** JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

At this point, `response.content` contains an HTML document of the NewRelic homepage, probably just their default error handling page. This is not good API error implementation, and I've filed a issue with NewRelic support on this.

# Recommendation #

1. create custom exceptions to represent server errors gracefully (e.g. `NewRelicAPIServerError`)
2. if `response.status != 200`, raise `NewRelicAPIServerError` with helpful message

# Scope #

Here are all the places that could use a safety check:
https://github.com/ambitioninc/newrelic-api/search?utf8=%E2%9C%93&q=%22return+response.json%22&type=Code

**Comment by micahhausler** [comment]
Good catch, thanks for the issue
