### ISSUE TITLE
Pagination link support

### ISSUE THREAD

**Issue by mwarkentin** [ambitioninc/newrelic-api#19]
Is there some way to be able to use the pagination links which are returned in the Link header with the response? 

```
Link: <https://api.newrelic.com/v2/servers.json?page=2>; rel="next", <https://api.newrelic.com/v2/servers.json?page=6>; rel="last"
```

I've got a lot of servers which I'd like to delete any which are not reporting, and I'm not really seeing a way to do that right now.

Thanks!

**Comment by micahhausler** [comment]
Thanks!

**Comment by micahhausler** [comment]
Thanks for opening this issue, I had my notifications messed up and didn't see this till now. 

If you don't mind my asking, how many servers did they paginate at? I'm not able to get any of responses to be paginated (and I have >120 applications)

**Comment by mwarkentin** [comment]
@micahhausler No problem, we hacked around it for now.

I believe they paginate at 200 servers. We're spinning up new servers on AWS for each release (eg. immutable infrastructure), so we rack up the server count quite quickly. :smile:

**Comment by micahhausler** [comment]
@mwarkentin what was your solution?

The requests Response object has a [`.links`](http://requests.readthedocs.org/en/latest/api/#requests.Response.links) that returns the link data. I'm leaning toward just injecting that into the response JSON. Do you have any thoughts?

**Comment by mwarkentin** [comment]
Here's what we ended up with:

```python
    # No way to determine total number of pages, or use the pagination headers
    # so just loop through 10 pages (up to 2000 servers). It handles pages which
    # don't exist gracefully.
    # https://github.com/ambitioninc/newrelic-api/issues/19

    # Loop through the pages backwards so that it can hit all of the servers in
    # one go (otherwise the pagination will skip some)
    for x in reversed(range(1, 11)):
        server_list = servers.list(page=x)
        for server in server_list['servers']:
            if server['reporting']:
                print "Not deleted (reporting): {} ({})".format(server['id'], server['name'])
            else:
                if dry_run:
                    print "Deleted (dry run): {} ({})".format(server['id'], server['name'])
                else:
                    servers.delete(server['id'])
                    print "Deleted (not reporting): {} ({})".format(server['id'], server['name'])
```

**Comment by mwarkentin** [comment]
@micahhausler I think passing through the requests `links` should be fine.
