### ISSUE TITLE
Support for returning data within a time range

### ISSUE THREAD

**Issue by adamstrawson** [ambitioninc/newrelic-api#26]
Would be great to introduce the ability to return data within a time range. 

This functionality isn't available in the New Relic API Explorer, but works if you're calling it manually via CURL as per this doc https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/extracting-metric-data

For example, the below would return the metrics between 05/09/2014 - 11/09/2015 in 1 hour periods;

```
-d'names[]=from=2015-09-05T10:00:00+00:00&to=2015-09-11T10:00:00+00:00&period=3600'
```

Python isn't my primary language, but I'lltry and submit a pull request myself unless someone thinks they can do it before me.

**Comment by micahhausler** [comment]
Sounds great! I'd be happy to add this

**Comment by adamstrawson** [comment]
Perfect, thanks @micahhausler :+1:
