### ISSUE TITLE
Project maintainer

### ISSUE THREAD

**Issue by lobsterdore** [ambitioninc/newrelic-api#36]
This repo is out of date with New Relics APIs and seems to be no longer maintained @ambitioninc do you have any plans to keep this project going?

I work on a fork (https://github.com/sansible/newrelic-api) where we have been adding support for the current NR APIs, would it be possible to get these changes merged over here? Looking at the PRs on this repo it seems that nothing has been merged for a while.

**Comment by travistruett** [comment]
Happy to merge your changes, sorry this is a project a previous employee created/maintained. We'd love to be more active but it's been a busy couple years :) 

If you want to open a PR I'll take a look and try to get merged quickly.

**Comment by bouktin** [comment]
Thank you @lobsterdore for reaching out.
@travistruett, would you consider adding some us as collaborators on this project?
Can you also confirm that the read-the-doc & PyPi linking to this github repos are still active?

Thanks
Thomas

**Comment by lobsterdore** [comment]
@travistruett thanks very much, I am just cleaning things up a bit in preparation for a PR, it's going to be a bit messy as there are a lot of commits

**Comment by travistruett** [comment]
Added you both as collaborators!

**Comment by bouktin** [comment]
Thank you Travis !

Le ven. 29 mars 2019 à 03:46, Travis Truett <notifications@github.com> a
écrit :

**Comment by lobsterdore** [comment]
Yes thanks very much! I should have a PR ready to go on Sunday, still needs a bit of tidying up.

**Comment by lobsterdore** [comment]
PR is out here - https://github.com/ambitioninc/newrelic-api/pull/37

**Comment by travistruett** [comment]
Hey David, I merged into develop and created a PR into Master where I was then going to create a release. Looks like tests are failing due to low coverage.

https://github.com/ambitioninc/newrelic-api/pull/38

Travis Truett
CEO | Ambition

**Comment by lobsterdore** [comment]
Thanks @travistruett, I will put another PR in for that.

**Comment by lobsterdore** [comment]
Quick fix is here @travistruett - https://github.com/ambitioninc/newrelic-api/pull/39

For some reason the test coverage is much higher locally than in Travis, I think this will need a bit of investigation to figure out why, for now I have had to lower it.

**Comment by lobsterdore** [comment]
Thanks for the help @travistruett
